### ISSUE TITLE
Error: Cannot find module '../../common/node/readManifest.js'

### ISSUE THREAD

**Issue by marceloavf** [geeklearningio/gl-vsts-tasks-build-scripts#9]
Build don't copy common node modules to task folder.

.js file
`const readManifest = require('../../common/node/readManifest.js')`

Error output
```
2018-01-23T17:35:33.7878102Z module.js:471
2018-01-23T17:35:33.7878102Z     throw err;
2018-01-23T17:35:33.7878102Z     ^
2018-01-23T17:35:33.7878102Z 
2018-01-23T17:35:33.7878102Z Error: Cannot find module '../../common/node/readManifest.js'
2018-01-23T17:35:33.7878102Z     at Function.Module._resolveFilename (module.js:469:15)
2018-01-23T17:35:33.7878102Z     at Function.Module._load (module.js:417:25)
2018-01-23T17:35:33.7878102Z     at Module.require (module.js:497:17)
2018-01-23T17:35:33.7878102Z     at require (internal/module.js:20:19)
2018-01-23T17:35:33.7878102Z     at Object.<anonymous> (C:\agent\_work\_tasks\GitHubReleasePublish_c2cf520f-2b1b-43b6-8b82-761fdd7c48ce\0.1.25000\githubReleasePublish.js:1:84)
2018-01-23T17:35:33.7878102Z     at Module._compile (module.js:570:32)
2018-01-23T17:35:33.7878102Z     at Object.Module._extensions..js (module.js:579:10)
2018-01-23T17:35:33.7878102Z     at Module.load (module.js:487:32)
2018-01-23T17:35:33.7888103Z     at tryModuleLoad (module.js:446:12)
2018-01-23T17:35:33.7888103Z     at Function.Module._load (module.js:438:3)
```

**Comment by sandorfr** [comment]
you need to have a package.json file in your extension folder with all your task dependencies listed.

**Comment by marceloavf** [comment]
Do you have some example @sandorfr, please

**Comment by sandorfr** [comment]
Yes any of our vsts extensions such as https://github.com/geeklearningio/gl-vsts-tasks-file-patch

**Comment by marceloavf** [comment]
Even if this is not from `node_modules` but from `Common/Node` ?
Can't make it work with JS :/

**Comment by sandorfr** [comment]
Ah get get what your saying :) no we don’t copy js files. Everything is
built around typescript. Why not use typescript?

**Comment by marceloavf** [comment]
I'll give a try, never used it before, thank you again!

**Comment by sandorfr** [comment]
It’s just modern JavaScript with typings ;) you should be fine. Use vs code
if you’re not already using it
